on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: '103.246.18.14'
        user: otters_tvs
        password: ${{ secrets.FTP_PWD }}
        remoteDir: "./wp-content/themes/tvs-sage/"
        
